# openapi2-functions.yaml
swagger: '2.0'
info:
  title: hello-world-vhixfkhy description
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://europe-west1-qwiklabs-gcp-02-017803ceab34.cloudfunctions.net/helloGET
      responses:
       '200':
          description: A successful response
          schema:
            type: string
